{% set name = "clpeak" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/krrishnarraj/clpeak/archive/refs/tags/{{ version }}.tar.gz
  sha256: c9ba6d46d17e94fe8074821047a6d59b011e600293ec27b8c52dd04370fcff5d

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - ninja
    - cmake
  host:
    - clhpp
    - libopencl-devel
test:
  commands:
    - clpeak -h

about:
  home: https://github.com/krrishnarraj/clpeak
  license: Unlicense
  license_file: LICENSE
  summary: 'A tool which profiles OpenCL devices to find their peak capacities'

extra:
  recipe-maintainers:
    - isuruf
